# -*- coding: utf-8 -*-
"""Notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RlaLXJf8DZQDGI3xR2iGlWplkWkpWlJq
"""

# import all necessery library

from __future__ import print_function
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torchvision import datasets, transforms
import numpy as np

from tqdm import tqdm



def dataloader(trainset, testset, gpu_batch_size, cpu_batch_size, workers, cuda):
   
    dataloader_args = dict(shuffle=True, batch_size=gpu_batch_size, num_workers=workers, pin_memory=True) if cuda else dict(shuffle=True, batch_size=cpu_batch_size)

    trainloader = torch.utils.data.DataLoader(trainset, **dataloader_args)
    testloader = torch.utils.data.DataLoader(testset, **dataloader_args)

    return trainloader, testloader